


INSERT INTO ITEM (ID,CREATOR,DATE,DESCRIPTION,PRICE,STATE) VALUES(1,'Christian','Fecha item','primer item',3.85,'ACTIVE');
INSERT INTO ITEM (ID,CREATOR,DATE,DESCRIPTION,PRICE,STATE) VALUES(2,'Christian','Fecha item','primer item',3.85,'ACTIVE');
INSERT INTO ITEM (ID,CREATOR,DATE,DESCRIPTION,PRICE,STATE) VALUES(3,'Christian','Fecha item','primer item',3.85,'ACTIVE');
INSERT INTO ITEM (ID,CREATOR,DATE,DESCRIPTION,PRICE,STATE) VALUES(4,'Christian','Fecha item','primer item',3.85,'ACTIVE');


